name: e2e

on:
  workflow_run:
    workflows:
      - '**'
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Event payload
        run: |
          jq . <<EOF
          ${{ toJSON(github.event) }}
          EOF
      - uses: lukascaska/datadog-actions-metrics@v1
        with:
          datadog-api-key: ${{ secrets.DATADOG_API_KEY }}
          collect-job-metrics: true
